version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_app
    ports:
      - 5435:5432
    env_file:
      - .env-non-dev
  redis:
    image: redis:7
    container_name: redis_app
    ports:
      - 5370:5370
  app:
    build: .
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 9999:8000
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
  celery:
    build: .
    env_file:
      - .env-non-dev
    container_name: celery_app
    command: ["/fastapi_app/docker/celery.sh", "celery"]
    depends_on:
      - redis

  flower:
    build: .
    env_file:
      - .env-non-dev
    container_name: flower_app
    command: ["/fastapi_app/docker/celery.sh", "flower"]
    depends_on:
      - redis
      - celery
    ports:
      - 8888:5555
