apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-app
  template:
    metadata:
      labels:
        app: celery-app
    spec:
      containers:
        - name: celery-app
          image: your_fastapi_image:latest # Replace with your FastAPI image
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-env
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-env
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-env
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: app-env
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASS
          command: ["/fastapi_app/docker/celery.sh", "celery"]

---
apiVersion: v1
kind: Service
metadata:
  name: celery-app
spec:
  type: ClusterIP
  selector:
    app: celery-app
